#Spring配置
spring:

  #Redis配置
  redis:
    host: 120.48.107.224
    port: 6379
    password:
    database: 0
    redisson:
      file: classpath:redisson-single.yml
    jedis:
      pool:
        max-active: 150
        max-wait: 100
        max-idle: 100
        min-idle: 50
    timeout: 5000ms
